# Generated by Django 3.0.4 on 2020-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('finnkode', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('pris', models.IntegerField()),
                ('totalpris', models.IntegerField()),
                ('areal', models.IntegerField()),
                ('megler', models.CharField(max_length=200)),
                ('sold', models.BooleanField(default=False)),
                ('actual_price', models.IntegerField(default=0)),
            ],
        ),
    ]
