# Generated by Django 3.0.7 on 2020-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('area1', models.CharField(max_length=100, null=True)),
                ('area2', models.CharField(blank=True, max_length=100, null=True)),
                ('boligtype', models.CharField(max_length=100, null=True)),
                ('code', models.IntegerField(null=True)),
                ('eierform', models.CharField(max_length=100, null=True)),
                ('fellesutgifter', models.FloatField(null=True)),
                ('m2', models.FloatField(null=True)),
                ('megler', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('scrape_datetime', models.DateTimeField(null=True)),
                ('soverom', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('totalpris', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
