# Generated by Django 3.0.7 on 2020-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='soverom',
            field=models.FloatField(null=True),
        ),
    ]
