# Generated by Django 3.0.4 on 2020-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='fellesgjeld',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
