# Generated by Django 3.0.4 on 2020-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_fellesgjeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='omrade1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
