# Generated by Django 3.0.4 on 2020-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_omrade2'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='byggear',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='etasje',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='fellesformue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='omkostninger',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
