# Generated by Django 3.0.4 on 2020-04-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200418_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='felleskost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
