# Generated by Django 3.0.4 on 2020-04-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_felleskost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='link',
            new_name='URL',
        ),
    ]
