# Generated by Django 3.0.4 on 2020-04-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200419_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='actual_price',
            new_name='salgspris',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='sold',
            new_name='solgt',
        ),
    ]
