# Generated by Django 3.0.4 on 2020-04-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200419_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='felleskost',
            new_name='felleskostnader',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='areal',
            new_name='primarareal',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='totalpris',
            new_name='totalkostnad',
        ),
    ]
