# Generated by Django 3.0.4 on 2020-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200419_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pris',
        ),
        migrations.AddField(
            model_name='property',
            name='prisantydning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='scrapedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='URL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='felleskostnader',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='finnkode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='megler',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='omrade1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='primarareal',
            field=models.IntegerField(null=True),
        ),
    ]
