# Generated by Django 3.0.4 on 2020-04-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20200420_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='URL',
            new_name='finnlink',
        ),
    ]
