from django.db import models

class Property(models.Model):

    address = models.CharField(max_length=200, null=True)
    area1 = models.CharField(max_length=100, null=True)
    area2 = models.CharField(max_length=100, null=True, blank=True)
    boligtype = models.CharField(max_length=100, null=True)
    code = models.IntegerField(null=True)
    eierform = models.CharField(max_length=100, null=True)	
    fellesutgifter = models.FloatField(null=True)
    m2 = models.FloatField(null=True)
    megler = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    scrape_datetime	= models.DateTimeField(null=True)
    soverom	= models.FloatField(null=True)
    title = models.CharField(max_length=400, null=True, blank=True)
    totalpris = models.FloatField(null=True, blank=True)
    url = models.CharField(max_length=200, null=True)
    sold = models.BooleanField(default=False)

    def __int__(self):
        return self.id

    ### Tidligere felter i denne modellen:
    #
    # scrapedate = models.DateTimeField(null=True)
    # finnlink = models.CharField(max_length=200, null=True)
    # tittel = models.CharField(max_length=400, null=True, blank=True)
    # adresse = models.CharField(max_length=200, null=True)
    # omrade1 = models.CharField(max_length=100, null=True)
    # omrade2 = models.CharField(max_length=100, null=True, blank=True)
    # megler = models.CharField(max_length=200, null=True)
    # prisantydning = models.FloatField(null=True)
    # fellesgjeld = models.FloatField(null=True, blank=True)
    # omkostninger = models.FloatField(null=True, blank=True)
    # totalkostnad = models.FloatField(null=True, blank=True)
    # felleskostnader = models.FloatField(null=True)
    # boligtype = models.CharField(max_length=100, null=True)
    # eierform = models.CharField(max_length=100, null=True)
    # primarareal = models.FloatField(null=True)
    # bruksareal = models.FloatField(null=True, blank=True)
    # etasje = models.FloatField(null=True, blank=True)
    # byggear = models.FloatField(null=True, blank=True)
    # energimerking = models.CharField(max_length=50, null=True)
    # tomteareal = models.FloatField(null=True, blank=True)
    # bruttoareal = models.FloatField(null=True, blank=True)
    # fellesformue = models.FloatField(null=True, blank=True)
    # eierskifteforsikring = models.BooleanField(null=True)
    # formuesverdi = models.FloatField(null=True, blank=True)
    # kommunenummer = models.FloatField(null=True, blank=True)
    # gardsnummer = models.FloatField(null=True, blank=True)
    # bolignummer = models.FloatField(null=True, blank=True)
    # seksjonsnummer = models.FloatField(null=True, blank=True)
    # BRLnavn = models.CharField(max_length=100, null=True)
    # BRLorgnr = models.CharField(max_length=100, null=True)
    # BRLandel = models.CharField(max_length=100, null=True)
    # beskrivelse = models.CharField(max_length=5000, null=True)
    # finnkode = models.IntegerField(null=True)
    # siste_endring = models.CharField(max_length=50, null=True)
    # referansenummer = models.CharField(max_length=50, null=True)
    # solgt = models.BooleanField(default=False)
    # salgspris = models.FloatField(null=True, blank=True)
    # forste_visning = models.DateField(null=True, blank=True)
    # siste_visning = models.DateField(null=True, blank=True)
    # status = models.CharField(max_length=100, null=True)